/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.GridLayout;
import model.Projeto;

/**
 *
 * @author Willighan
 */
public class CardTarefasProjeto extends javax.swing.JPanel {

    /**
     * Creates new form CardTarefasProjeto
     */
    public CardTarefasProjeto() {
        initComponents();
        
        this.painelGrid.setLayout(new GridLayout(0,1,10,10));
        
    }
    
    public void setDados(Projeto projeto){
        
        this.lblNomeProjeto.setText(projeto.getNome());
        this.lblNomeLider.setText(projeto.getLider().getNome());
        
    }
    
    public void atualizar(){
        this.painelGrid.revalidate();
        this.painelGrid.repaint();
    }
    
    public void adicionarCardTarefa(CardTarefaIndividual cardTarefa) {
        this.painelGrid.add(cardTarefa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProjeto = new javax.swing.JLabel();
        lblNomeLider = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelGrid = new javax.swing.JPanel();

        lblNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNomeProjeto.setText("jLabel1");

        lblNomeLider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeLider.setText("jLabel2");

        javax.swing.GroupLayout painelGridLayout = new javax.swing.GroupLayout(painelGrid);
        painelGrid.setLayout(painelGridLayout);
        painelGridLayout.setHorizontalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        painelGridLayout.setVerticalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeLider)
                .addContainerGap(249, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProjeto)
                    .addComponent(lblNomeLider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeLider;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JPanel painelGrid;
    // End of variables declaration//GEN-END:variables
}
