/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Projeto;

/**
 *
 * @author Willighan
 */
public class CardProjetos extends javax.swing.JPanel {

    /**
     * Creates new form CardProjetos
     */
    public CardProjetos() {
        initComponents();
    }
    
    public void setDadosProjeto(Projeto projeto){
        
        this.lblNomeProjeto.setText(projeto.getNome());
        this.lblNomeLider.setText(projeto.getLider().getNome());
        this.lblDescricao.setText(projeto.getDescricao());
        this.barraProgresso.setValue(projeto.porcentagemConcluida());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProjeto = new javax.swing.JLabel();
        lblNomeLider = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        barraProgresso = new javax.swing.JProgressBar();

        lblNomeProjeto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNomeProjeto.setText("jLabel1");

        lblNomeLider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeLider.setText("jLabel1");

        lblDescricao.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeProjeto)
                                    .addComponent(lblNomeLider)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblDescricao)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(barraProgresso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeLider)
                .addGap(18, 18, 18)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeLider;
    private javax.swing.JLabel lblNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
