/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.MembrosProjetoDAO;
import DAO.ProjetoDAO;
import DAO.UsuariosDAO;
import controle.NavegacaoMediator;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Projeto;
import model.Usuario;
import util.SessaoUsuario;

/**
 *
 * @author Willighan
 */
public class PainelCriarProjeto extends javax.swing.JPanel {

    /**
     * Creates new form PainelCriarProjeto
     */
    
    private NavegacaoMediator mediator;
    
    public PainelCriarProjeto(NavegacaoMediator mediator) {
        initComponents();
        
        this.mediator = mediator;
        
        listaUsuarios.setModel(new DefaultListModel<>());
        carregarUsuariosNaLista();
    }
    
    public void carregarUsuariosNaLista() {
        
        UsuariosDAO usuarioDAO = new UsuariosDAO();
        List<Usuario> usuarios = usuarioDAO.listarUsuarios();

        DefaultListModel<String> modelo = (DefaultListModel<String>) listaUsuarios.getModel();
        modelo.clear(); // Limpa a lista antes de adicionar os dados

        for (Usuario u : usuarios) {
            modelo.addElement(u.getNome()); // Adiciona apenas o nome do usuário
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfDescricaoProjeto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfNomeProjeto = new javax.swing.JTextField();
        formatedTxtfCampoDataConclusao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCriarProjeto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome Projeto:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Descrição:");

        formatedTxtfCampoDataConclusao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data previsão de conclusão:");

        btnCriarProjeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCriarProjeto.setText("Criar Projeto");
        btnCriarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarProjetoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Novo Projeto:");

        jScrollPane1.setViewportView(listaUsuarios);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Membros do Projeto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfDescricaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtfNomeProjeto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(formatedTxtfCampoDataConclusao))))))
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnCriarProjeto)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfDescricaoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formatedTxtfCampoDataConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarProjeto)
                    .addComponent(btnCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarProjetoActionPerformed
        
        //TODO adicionar verificação dos campos
        
        ProjetoDAO projetoDAO = new ProjetoDAO();
        MembrosProjetoDAO membrosProjetoDAO = new MembrosProjetoDAO();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataAtual = LocalDate.now().format(formatter);

        Projeto projeto = new Projeto(
            txtfNomeProjeto.getText(),
            txtfDescricaoProjeto.getText(),
            dataAtual,
            formatedTxtfCampoDataConclusao.getText(),
            SessaoUsuario.getUsuarioLogado().getIdUsuario()
        );
        
        int idProjetoGerado = projetoDAO.inserirProjetoRetornandoId(projeto);
        
        List<String> usuariosSelecionados = listaUsuarios.getSelectedValuesList();
        
        UsuariosDAO usuariosDAO = new UsuariosDAO();

        for(String nomeUsuario: usuariosSelecionados){
            
            membrosProjetoDAO.inserirMembro(idProjetoGerado, usuariosDAO.buscarUsuarioPorNome(nomeUsuario).getIdUsuario());
            
        }
        
        JOptionPane.showMessageDialog(null, "Prjeto Criado com sucesso");
        
        mediator.getTelaPrincipal().mostrarPainel("Projetos");
        
    }//GEN-LAST:event_btnCriarProjetoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        mediator.getTelaPrincipal().mostrarPainel("Projetos");
        
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCriarProjeto;
    private javax.swing.JFormattedTextField formatedTxtfCampoDataConclusao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JTextField txtfDescricaoProjeto;
    private javax.swing.JTextField txtfNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
