/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controle.NavegacaoMediator;
import java.awt.GridLayout;
import model.Projeto;
import model.Tarefa;

/**
 *
 * @author Aluno
 */
public class PainelVisualizarProjeto extends javax.swing.JPanel {

    /**
     * Creates new form PainelVisualizarProjeto
     */
    
    private Projeto projeto;
    
    public PainelVisualizarProjeto(Projeto projeto, NavegacaoMediator mediator) {
        initComponents();
        
        this.painelGrid.setLayout(new GridLayout(0,1,10,10));
        
    }
    
    public void setDados(Projeto projeto){
        
        this.lblNomeProjeto.setText(projeto.getNome());
        this.lblNomeLider.setText(projeto.getLider().getNome());
        this.lblDescricao.setText(projeto.getDescricao());
        this.jProgressBar1.setValue(projeto.porcentagemConcluida());
        
        if(projeto.getTarefas().isEmpty()){
            System.err.println("Tarefas do projeto: "+projeto.getNome()+ "vazio");
        }
        
        for(Tarefa tarefa : projeto.getTarefas()){
         
            CardTarefaIndividual cardTarefaIndividual = new CardTarefaIndividual();
            cardTarefaIndividual.setDados(tarefa);
            
            painelGrid.add(cardTarefaIndividual);
            
        }
        
        painelGrid.revalidate();
        painelGrid.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProjeto = new javax.swing.JLabel();
        lblNomeLider = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelGrid = new javax.swing.JPanel();

        lblNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNomeProjeto.setText("jLabel1");

        lblNomeLider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeLider.setText("jLabel1");

        lblDescricao.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Progresso:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Tarefas:");

        javax.swing.GroupLayout painelGridLayout = new javax.swing.GroupLayout(painelGrid);
        painelGrid.setLayout(painelGridLayout);
        painelGridLayout.setHorizontalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        painelGridLayout.setVerticalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeProjeto)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDescricao))
                            .addComponent(lblNomeLider)))
                    .addComponent(jLabel1)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeLider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeLider;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JPanel painelGrid;
    // End of variables declaration//GEN-END:variables
}
