/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.ProjetoDAO;
import controle.NavegacaoMediator;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import model.Projeto;
import util.SessaoUsuario;

/**
 *
 * @author Willighan
 */
public class PainelProjetos extends javax.swing.JPanel {

    /**
     * Creates new form PainelProjetos
     */
    
    private NavegacaoMediator mediator;
    
    public PainelProjetos(NavegacaoMediator mediator) {
        initComponents();
        
        this.mediator = mediator;
        
        this.painelGrid.setLayout(new GridLayout(0,2,10,10));
        
        //carregarDados();
        
    }
    
    public void carregarDados(){
        
        System.out.println("Tentando carregar dados dos projetos");
        
        painelGrid.removeAll();
        
        List<Projeto> projetos;
        
        int idUsuarioLogado = SessaoUsuario.getUsuarioLogado().getIdUsuario();
        
        ProjetoDAO projetoDAO = new ProjetoDAO();
        
        if(this.rBtnMeusProjetos.isSelected()){
            projetos = projetoDAO.buscarProjetosDoLider(idUsuarioLogado);
        }else if(this.rBtnMembroProjetos.isSelected()){
            projetos = projetoDAO.buscarProjetosDoMembro(idUsuarioLogado);
        }   else {
            projetos = new ArrayList<>();
        }
        
        System.out.println("Debuging do carregamento de dados dos projetos\n-------------------------\n");
        
        if(projetos.isEmpty()){
            System.err.println("Array de resultado da busca vazio");
        }
        
        for (Projeto projeto : projetos) {
            System.out.println(projeto.toString());
            CardProjetos card = new CardProjetos(projeto, mediator);
            card.setDadosProjeto(projeto);
            painelGrid.add(card);
        }

        painelGrid.revalidate();
        painelGrid.repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnNovoProjeto = new javax.swing.JButton();
        rBtnMeusProjetos = new javax.swing.JRadioButton();
        rBtnMembroProjetos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelGrid = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1047, 457));

        btnNovoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNovoProjeto.setText("Novo Projeto");
        btnNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProjetoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnMeusProjetos);
        rBtnMeusProjetos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rBtnMeusProjetos.setSelected(true);
        rBtnMeusProjetos.setText("Meus Projetos:");
        rBtnMeusProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMeusProjetosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnMembroProjetos);
        rBtnMembroProjetos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rBtnMembroProjetos.setText("Projetos em que faço parte:");
        rBtnMembroProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMembroProjetosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGridLayout = new javax.swing.GroupLayout(painelGrid);
        painelGrid.setLayout(painelGridLayout);
        painelGridLayout.setHorizontalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        painelGridLayout.setVerticalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoProjeto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rBtnMeusProjetos)
                        .addGap(18, 18, 18)
                        .addComponent(rBtnMembroProjetos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoProjeto)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnMeusProjetos)
                    .addComponent(rBtnMembroProjetos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnMeusProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMeusProjetosActionPerformed
        System.out.println("Meus projetos selecionado");
        carregarDados();
    }//GEN-LAST:event_rBtnMeusProjetosActionPerformed

    private void rBtnMembroProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMembroProjetosActionPerformed
        System.out.println("Projetos em que faço parte selecionado");
        carregarDados();
    }//GEN-LAST:event_rBtnMembroProjetosActionPerformed

    private void btnNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProjetoActionPerformed
        
        mediator.abrirCriacaoProjeto();
        
    }//GEN-LAST:event_btnNovoProjetoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoProjeto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelGrid;
    private javax.swing.JRadioButton rBtnMembroProjetos;
    private javax.swing.JRadioButton rBtnMeusProjetos;
    // End of variables declaration//GEN-END:variables
}
