/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.ComentarioDAO;
import DAO.TarefaDAO;
import java.awt.GridLayout;
import model.Comentario;
import model.Tarefa;
import util.SessaoUsuario;

/**
 *
 * @author Willighan
 */
public class PainelVisualizarTarefa extends javax.swing.JPanel {

    /**
     * Creates new form PainelVisualizarTarefa
     */
    private Tarefa tarefa;
    private ComentarioDAO comentarioDAO = new ComentarioDAO();
    
    public PainelVisualizarTarefa(Tarefa tarefa) {
        initComponents();
        
        this.tarefa = tarefa;
        
        this.painelGrid.setLayout(new GridLayout(0,1,10,10));
        
        if(SessaoUsuario.getUsuarioLogado().getIdUsuario() != tarefa.getIdUsuarioResponsavel()){
            this.cmbxStatusTarefa.setVisible(false);
        }
        
    }
    
    public void setDados(){
        
        this.lblNomeTarefa.setText(tarefa.getTitulo());
        this.lblNomeResponsável.setText(tarefa.getUsuarioResponsavel().getNome());
        this.lblDescricaoTarefa.setText(tarefa.getDescricao());
        this.lblStatusTarefa.setText(tarefa.getStatus().getDescricao());
        
    }
    
    public void recaregarDados(){
        
        TarefaDAO tarefaDAO = new TarefaDAO();
        this.tarefa = tarefaDAO.buscarTarefa(tarefa);
        
        setDados();
        
    }
    
    public void carregarComentarios(){
        
        this.painelGrid.removeAll();
        
        for(Comentario comentario : comentarioDAO.buscarPorTarefa(tarefa.getIdTarefa())){
            
            CardComentario cardComentario = new CardComentario();
            cardComentario.setDados(comentario);
            
            this.painelGrid.add(cardComentario);

        }
        
        painelGrid.revalidate();
        painelGrid.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTarefa = new javax.swing.JLabel();
        lblNomeResponsável = new javax.swing.JLabel();
        lblDescricaoTarefa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStatusTarefa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelGrid = new javax.swing.JPanel();
        txtfCampoComentario = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbxStatusTarefa = new javax.swing.JComboBox<>();

        lblNomeTarefa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNomeTarefa.setText("jLabel1");

        lblNomeResponsável.setText("jLabel2");

        lblDescricaoTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescricaoTarefa.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Status:");

        lblStatusTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatusTarefa.setText("jLabel2");

        javax.swing.GroupLayout painelGridLayout = new javax.swing.GroupLayout(painelGrid);
        painelGrid.setLayout(painelGridLayout);
        painelGridLayout.setHorizontalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        painelGridLayout.setVerticalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelGrid);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Comentários:");

        cmbxStatusTarefa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Progresso", "Concluída" }));
        cmbxStatusTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxStatusTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeResponsável))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatusTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbxStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescricaoTarefa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfCampoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComentar))
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTarefa)
                    .addComponent(lblNomeResponsável))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricaoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatusTarefa)
                    .addComponent(cmbxStatusTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCampoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComentar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        
        String conteudoComentario = this.txtfCampoComentario.getText();
        
        Comentario comentario = new Comentario(conteudoComentario, tarefa.getIdTarefa(), SessaoUsuario.getUsuarioLogado().getIdUsuario());
        
        comentarioDAO.inserir(comentario);
        
        carregarComentarios();
        
        this.txtfCampoComentario.setText("");
        
    }//GEN-LAST:event_btnComentarActionPerformed

    private void cmbxStatusTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxStatusTarefaActionPerformed
        
        System.out.println("view.PainelVisualizarTarefa.cmbxStatusTarefaActionPerformed()");
        
        TarefaDAO tarefaDAO = new TarefaDAO();
        String statusAtual = tarefa.getStatus().getDescricao();
        int indiceSelecionado = cmbxStatusTarefa.getSelectedIndex();
        
        // Verificações de segurança
        if (tarefa == null || tarefa.getStatus() == null || tarefa.getStatus().getDescricao() == null) {
            System.err.println("Tarefa ou status da tarefa está nulo.");
            return;
        }
        
        // índice 0 = "Em Progresso", índice 1 = "Concluída"
        switch (statusAtual) {
        case "Em Progresso":
            if (indiceSelecionado == 1) {
                tarefaDAO.concluirTarefa(tarefa);
                System.out.println("Tarefa concluída.");
            }
            break;

        case "Concluída":
            if (indiceSelecionado == 0) {
                tarefaDAO.reabrirTarefa(tarefa);
                System.out.println("Tarefa reaberta.");
            }
            break;
            
        case "Atrasada":
            if (indiceSelecionado == 1) {
                tarefaDAO.concluirTarefa(tarefa);
                System.out.println("Tarefa concluída.");
            }
            break;

        default:
            System.out.println("Status atual não reconhecido: " + statusAtual);
        }
        
        //TODO ajustar o recarregamento do status
        
        recaregarDados();
        
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_cmbxStatusTarefaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JComboBox<String> cmbxStatusTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricaoTarefa;
    private javax.swing.JLabel lblNomeResponsável;
    private javax.swing.JLabel lblNomeTarefa;
    private javax.swing.JLabel lblStatusTarefa;
    private javax.swing.JPanel painelGrid;
    private javax.swing.JTextField txtfCampoComentario;
    // End of variables declaration//GEN-END:variables
}
