/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.GridLayout;
import java.util.List;

import model.Projeto;

/**
 *
 * @author Willighan
 */
public class PainelTarefas extends javax.swing.JPanel {

    /**
     * Creates new form PainelTarefas
     */
    public PainelTarefas() {
        initComponents();
        
        this.painelGrid.setLayout(new GridLayout(0,2,10,10));
        
        //Valores para testes
        
        Projeto projeto1 = new Projeto("Projeto teste", "Descrição", "22/06/205", "24/06/2025", 1);
        Projeto projeto2 = new Projeto("Projeto teste 2", "Descrição 2", "22/06/205", "24/06/2025", 1);
        Projeto projeto3 = new Projeto("Projeto teste 3", "Descrição 3", "22/06/205", "24/06/2025", 2);
        Projeto projeto4 = new Projeto("Projeto teste 4", "Descrição 4", "22/06/205", "24/06/2025", 1);
        Projeto projeto5 = new Projeto("Projeto teste 5", "Descrição 5", "22/06/205", "24/06/2025", 2);
        Projeto projeto6 = new Projeto("Projeto teste 6", "Descrição 6", "22/06/205", "24/06/2025", 2);
        Projeto projeto7 = new Projeto("Projeto teste 7", "Descrição 7", "22/06/205", "24/06/2025", 1);
        Projeto projeto8 = new Projeto("Projeto teste 8", "Descrição 8", "22/06/205", "24/06/2025", 2);
        
        List<Projeto> projetos = List.of(projeto1, projeto2, projeto3, projeto4, projeto5, projeto6, projeto7, projeto8);

        for (Projeto projeto : projetos) {
            CardProjetos card = new CardProjetos();
            card.setDadosProjeto(projeto);
            painelGrid.add(card);
        }

        painelGrid.revalidate();
        painelGrid.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelGrid = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1047, 457));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Minhas Tarefas:");

        javax.swing.GroupLayout painelGridLayout = new javax.swing.GroupLayout(painelGrid);
        painelGrid.setLayout(painelGridLayout);
        painelGridLayout.setHorizontalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        painelGridLayout.setVerticalGroup(
            painelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelGrid;
    // End of variables declaration//GEN-END:variables
}
